spring.application.name=dockerdemo
server.port=${PORT:8080}

# File Database Directory (stores text files for users & records)
app.database.dir=./data

# Thymeleaf development settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
